### ISSUE TITLE
1.x release to point to new location

### ISSUE THREAD

**Issue by minchinweb** [MinchinWeb/minchin.pelican.jinja_filters#7]
As the package name changed, release one more 1.x release pointing to the new location.

**Comment by justinmayer** [comment]
The new release has been published: https://pypi.org/project/pelican-jinja-filters/

GitHub CI is still beta-level quality, so there are times it behaves erratically, [as it did in this case](https://github.com/pelican-plugins/jinja-filters/runs/1011821138?check_suite_focus=true#step:5:51). Using the same PyPI token that produced an error in GitHub CI (`HTTP Error 403: Invalid API Token: invalid macaroon signature`) and manually publishing via the exact same Poetry version and command invocation… yielded success. Hopefully GitHub will work out its unpredictable behavior sometime soon. 🤷‍♂️

**Comment by minchinweb** [comment]
Closed with the release of version 1.1.0; see https://github.com/pelican-plugins/jinja-filters/commit/7ff7baf6a5bf1f1f4cf319264276b424cb6cb89a
